# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 515)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(130, 30, 661, 421))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 111, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.openvideo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openvideo.setObjectName("openvideo")
        self.verticalLayout.addWidget(self.openvideo)
        self.action_category = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.action_category.setToolTip("")
        self.action_category.setEditable(False)
        self.action_category.setObjectName("action_category")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.action_category.addItem("")
        self.verticalLayout.addWidget(self.action_category)
        self.camera = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.camera.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.camera.setToolTipDuration(-2)
        self.camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camera.setObjectName("camera")
        self.camera.addItem("")
        self.camera.addItem("")
        self.verticalLayout.addWidget(self.camera)
        self.open_camera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_camera.setObjectName("open_camera")
        self.verticalLayout.addWidget(self.open_camera)
        self.close_camera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.close_camera.setObjectName("close_camera")
        self.verticalLayout.addWidget(self.close_camera)
        self.start_conuting = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_conuting.setObjectName("start_conuting")
        self.verticalLayout.addWidget(self.start_conuting)
        self.stop_counting = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stop_counting.setObjectName("stop_counting")
        self.verticalLayout.addWidget(self.stop_counting)

        self.retranslateUi(MainWindow)
        self.action_category.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.openvideo.setText(_translate("MainWindow", "打开视频文件"))
        self.action_category.setCurrentText(_translate("MainWindow", "动作类别"))
        self.action_category.setItemText(0, _translate("MainWindow", "动作类别"))
        self.action_category.setItemText(1, _translate("MainWindow", "front_raise"))
        self.action_category.setItemText(2, _translate("MainWindow", "pull_up"))
        self.action_category.setItemText(3, _translate("MainWindow", "squat"))
        self.action_category.setItemText(4, _translate("MainWindow", "bench_pressing"))
        self.action_category.setItemText(5, _translate("MainWindow", "jump_jack"))
        self.action_category.setItemText(6, _translate("MainWindow", "situp"))
        self.action_category.setItemText(7, _translate("MainWindow", "push_up"))
        self.action_category.setItemText(8, _translate("MainWindow", "pommelhorse"))
        self.camera.setItemText(0, _translate("MainWindow", "本地相机"))
        self.camera.setItemText(1, _translate("MainWindow", "外置相机"))
        self.open_camera.setText(_translate("MainWindow", "打开摄像头"))
        self.close_camera.setText(_translate("MainWindow", "关闭摄像头"))
        self.start_conuting.setText(_translate("MainWindow", "开始计数"))
        self.stop_counting.setText(_translate("MainWindow", "停止计数"))
