# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # 创建垂直布局，包含所有组件
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(10, 10, 10, 10)
        self.mainLayout.setSpacing(20)

        # 水平布局：包含两个标签
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(40)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background:rgb(83, 82, 82)")
        self.label_2.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background:rgb(83, 82, 82)")
        self.label_3.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addWidget(self.label_3)
        self.mainLayout.addLayout(self.horizontalLayout)

        # 网格布局：包含按钮
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(60, 0, 60, 0)
        self.gridLayout.setHorizontalSpacing(120)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setAutoRepeatDelay(300)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.mainLayout.addLayout(self.gridLayout)

        MainWindow.setCentralWidget(self.centralwidget)

        # 菜单栏
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menu)
        self.menu_4.setObjectName("menu_4")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # 动作菜单
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setCheckable(True)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setCheckable(True)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setCheckable(True)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setCheckable(True)
        self.action_10.setObjectName("action_10")
        self.actionfront_raise = QtWidgets.QAction(MainWindow)
        self.actionfront_raise.setCheckable(True)
        self.actionfront_raise.setObjectName("actionfront_raise")
        self.actionpull_up = QtWidgets.QAction(MainWindow)
        self.actionpull_up.setCheckable(True)
        self.actionpull_up.setObjectName("actionpull_up")
        self.actionsquat = QtWidgets.QAction(MainWindow)
        self.actionsquat.setCheckable(True)
        self.actionsquat.setObjectName("actionsquat")
        self.actionbench_pressing = QtWidgets.QAction(MainWindow)
        self.actionbench_pressing.setCheckable(True)
        self.actionbench_pressing.setObjectName("actionbench_pressing")
        self.actionjump_jack = QtWidgets.QAction(MainWindow)
        self.actionjump_jack.setCheckable(True)
        self.actionjump_jack.setObjectName("actionjump_jack")
        self.actionsitup = QtWidgets.QAction(MainWindow)
        self.actionsitup.setCheckable(True)
        self.actionsitup.setObjectName("actionsitup")
        self.actionpush_up = QtWidgets.QAction(MainWindow)
        self.actionpush_up.setCheckable(True)
        self.actionpush_up.setObjectName("actionpush_up")
        self.actionpommelhorse = QtWidgets.QAction(MainWindow)
        self.actionpommelhorse.setCheckable(True)
        self.actionpommelhorse.setObjectName("actionpommelhorse")

        # 创建QActionGroup以确保菜单中的选项互斥
        self.group_3 = QtWidgets.QActionGroup(MainWindow)
        self.group_3.setExclusive(True)  # 设置为互斥模式
        self.group_4 = QtWidgets.QActionGroup(MainWindow)
        self.group_4.setExclusive(True)

        # 将menu_3中的QAction添加到group_3
        self.group_3.addAction(self.action_7)
        self.group_3.addAction(self.action_8)
        self.group_3.addAction(self.action_9)
        self.group_3.addAction(self.action_10)

        # 将menu_4中的QAction添加到group_4
        self.group_4.addAction(self.actionfront_raise)
        self.group_4.addAction(self.actionpull_up)
        self.group_4.addAction(self.actionsquat)
        self.group_4.addAction(self.actionbench_pressing)
        self.group_4.addAction(self.actionjump_jack)
        self.group_4.addAction(self.actionsitup)
        self.group_4.addAction(self.actionpush_up)
        self.group_4.addAction(self.actionpommelhorse)

        # 菜单动作绑定
        self.menu_3.addAction(self.action_7)
        self.menu_3.addAction(self.action_8)
        self.menu_3.addAction(self.action_9)
        self.menu_3.addAction(self.action_10)
        self.menu_4.addAction(self.actionfront_raise)
        self.menu_4.addAction(self.actionpull_up)
        self.menu_4.addAction(self.actionsquat)
        self.menu_4.addAction(self.actionbench_pressing)
        self.menu_4.addAction(self.actionjump_jack)
        self.menu_4.addAction(self.actionsitup)
        self.menu_4.addAction(self.actionpush_up)
        self.menu_4.addAction(self.actionpommelhorse)
        self.menu.addAction(self.menu_3.menuAction())
        self.menu.addAction(self.menu_4.menuAction())
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        # 将菜单动作连接到槽函数
        self.actionfront_raise.triggered.connect(lambda: MainWindow.update_motion(self.actionfront_raise.text()))
        self.actionpull_up.triggered.connect(lambda: MainWindow.update_motion(self.actionpull_up.text()))
        self.actionsquat.triggered.connect(lambda: MainWindow.update_motion(self.actionsquat.text()))
        self.actionbench_pressing.triggered.connect(lambda: MainWindow.update_motion(self.actionbench_pressing.text()))
        self.actionjump_jack.triggered.connect(lambda: MainWindow.update_motion(self.actionjump_jack.text()))
        self.actionsitup.triggered.connect(lambda: MainWindow.update_motion(self.actionsitup.text()))
        self.actionpush_up.triggered.connect(lambda: MainWindow.update_motion(self.actionpush_up.text()))
        self.actionpommelhorse.triggered.connect(lambda: MainWindow.update_motion(self.actionpommelhorse.text()))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "开启摄像头"))
        self.pushButton_2.setText(_translate("MainWindow", "开始识别"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "设置曲线图位置"))
        self.menu_4.setTitle(_translate("MainWindow", "动作识别类型"))
        self.menu_2.setTitle(_translate("MainWindow", "调整"))
        self.action.setText(_translate("MainWindow", "显示人体定位点"))
        self.action_2.setText(_translate("MainWindow", "显示姿态曲线"))
        self.action_3.setText(_translate("MainWindow", "显示识别动作类型"))
        self.action_4.setText(_translate("MainWindow", "显示重复动作个数"))
        self.action_6.setText(_translate("MainWindow", "设置字号大小"))
        self.action_7.setText(_translate("MainWindow", "左上"))
        self.action_8.setText(_translate("MainWindow", "左下"))
        self.action_9.setText(_translate("MainWindow", "右上"))
        self.action_10.setText(_translate("MainWindow", "右下"))
        self.actionfront_raise.setText(_translate("MainWindow", "front_raise"))
        self.actionpull_up.setText(_translate("MainWindow", "pull_up"))
        self.actionsquat.setText(_translate("MainWindow", "squat"))
        self.actionbench_pressing.setText(_translate("MainWindow", "bench_pressing"))
        self.actionjump_jack.setText(_translate("MainWindow", "jump_jack"))
        self.actionsitup.setText(_translate("MainWindow", "situp"))
        self.actionpush_up.setText(_translate("MainWindow", "push_up"))
        self.actionpommelhorse.setText(_translate("MainWindow", "pommelhorse"))

